'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WinFreeReg.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property appico() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("appico", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property help() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("help", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Church records for {1} in {0} have been updated..
        '''</summary>
        Friend ReadOnly Property msgChurchesUpdated() As String
            Get
                Return ResourceManager.GetString("msgChurchesUpdated", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You have elected to delete the file {0}. Are you absolutely sure that you really want to do this?.
        '''</summary>
        Friend ReadOnly Property msgConfirmDeleteFile() As String
            Get
                Return ResourceManager.GetString("msgConfirmDeleteFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You have elected to delete the current record. Are you sure that you reallly want to do this?.
        '''</summary>
        Friend ReadOnly Property msgConfirmDeleteObject() As String
            Get
                Return ResourceManager.GetString("msgConfirmDeleteObject", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This will remove the selected file ({0}) from the FreeREG database. The data will no longer exist in the database and will not be found by researchers. Are you absolutely certain that you want to do this?.
        '''</summary>
        Friend ReadOnly Property msgConfirmRemoveDatabaseFile() As String
            Get
                Return ResourceManager.GetString("msgConfirmRemoveDatabaseFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The County records have been refreshed..
        '''</summary>
        Friend ReadOnly Property msgCountiesRefreshed() As String
            Get
                Return ResourceManager.GetString("msgCountiesRefreshed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This is going to be the explanation for the error.
        '''</summary>
        Friend ReadOnly Property msgError() As String
            Get
                Return ResourceManager.GetString("msgError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to To start a new file requires that a File Code is allocated. This can either be done on a once-off basis per file, or a code can be allocated on the Church record and then used on each file that is created for that Church..
        '''</summary>
        Friend ReadOnly Property msgFileCodeIsRequired() As String
            Get
                Return ResourceManager.GetString("msgFileCodeIsRequired", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The file {0} has been deleted and is currently in the Recycle Bin..
        '''</summary>
        Friend ReadOnly Property msgFileRecycled() As String
            Get
                Return ResourceManager.GetString("msgFileRecycled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The selected file does not appear to be a valid Transcription FIle, even though outwardly the name and extension would indicate that it is. You can not open this file without examining it, and correcting it, outside of this program..
        '''</summary>
        Friend ReadOnly Property msgInvalidFileFormat() As String
            Get
                Return ResourceManager.GetString("msgInvalidFileFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You have successfully logged in to the FreeREGserver..
        '''</summary>
        Friend ReadOnly Property msgLoggedIn() As String
            Get
                Return ResourceManager.GetString("msgLoggedIn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You are trying to add a new record to the table, but, the File Value is identical to a previously added record..
        '''</summary>
        Friend ReadOnly Property msgNewRecordNotUnique() As String
            Get
                Return ResourceManager.GetString("msgNewRecordNotUnique", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No Batches have been uploaded to FreeREG.
        '''</summary>
        Friend ReadOnly Property msgNoBatchesForUser() As String
            Get
                Return ResourceManager.GetString("msgNoBatchesForUser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The selected Place ({0}) has no Churches. You can not select this place..
        '''</summary>
        Friend ReadOnly Property msgNoChurchesForPlace() As String
            Get
                Return ResourceManager.GetString("msgNoChurchesForPlace", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Place records for {0} have been updated..
        '''</summary>
        Friend ReadOnly Property msgPlacesUpdated() As String
            Get
                Return ResourceManager.GetString("msgPlacesUpdated", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Register Type records have been refreshed.
        '''</summary>
        Friend ReadOnly Property msgRegisterTypesRefreshed() As String
            Get
                Return ResourceManager.GetString("msgRegisterTypesRefreshed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The file has errors in it. Do you wish to save the file with the errors in it..
        '''</summary>
        Friend ReadOnly Property msgSaveFileWithErrors() As String
            Get
                Return ResourceManager.GetString("msgSaveFileWithErrors", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There are unsaved changes, do you wish to save these changes before closing the file?.
        '''</summary>
        Friend ReadOnly Property msgUnsavedChanges() As String
            Get
                Return ResourceManager.GetString("msgUnsavedChanges", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
