'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5485
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WinREG.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Burial Age is badly formatted.
        '''</summary>
        Friend ReadOnly Property err0004() As String
            Get
                Return ResourceManager.GetString("err0004", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Age of the Bride is invalid. The accepted format is: [number][d|w|m], [number]y[number][d|w|m], minor, of age, full age or of full age..
        '''</summary>
        Friend ReadOnly Property err0005() As String
            Get
                Return ResourceManager.GetString("err0005", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Age of the Groom is invalid. The accepted format is: [number][d|w|m], [number]y[number][d|w|m], minor, of age, full age or of full age..
        '''</summary>
        Friend ReadOnly Property err0006() As String
            Get
                Return ResourceManager.GetString("err0006", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The entered date is badly formatted.
        '''</summary>
        Friend ReadOnly Property err0011() As String
            Get
                Return ResourceManager.GetString("err0011", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid month name abbreviation.
        '''</summary>
        Friend ReadOnly Property err0013() As String
            Get
                Return ResourceManager.GetString("err0013", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A non-numeric month name must be 3 or more characters in length.
        '''</summary>
        Friend ReadOnly Property err0014() As String
            Get
                Return ResourceManager.GetString("err0014", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to In September 1752, the 3rd through to 13th inclusive were omitted from the calendar.
        '''</summary>
        Friend ReadOnly Property err0015() As String
            Get
                Return ResourceManager.GetString("err0015", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Month is invalid when used in double-dating. Only Jan, Feb and Mar are allowed..
        '''</summary>
        Friend ReadOnly Property err0016() As String
            Get
                Return ResourceManager.GetString("err0016", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to March 25th and after can not be double-dated.
        '''</summary>
        Friend ReadOnly Property err0017() As String
            Get
                Return ResourceManager.GetString("err0017", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Turn of century should be expressed with 00.
        '''</summary>
        Friend ReadOnly Property err0018() As String
            Get
                Return ResourceManager.GetString("err0018", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The double-year entry is invalid. The second part should be one greater than the first part..
        '''</summary>
        Friend ReadOnly Property err0019() As String
            Get
                Return ResourceManager.GetString("err0019", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Double-year can not be greater than 99.
        '''</summary>
        Friend ReadOnly Property err0020() As String
            Get
                Return ResourceManager.GetString("err0020", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Double-year must be numeric.
        '''</summary>
        Friend ReadOnly Property err0021() As String
            Get
                Return ResourceManager.GetString("err0021", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Year must be numeric.
        '''</summary>
        Friend ReadOnly Property err0022() As String
            Get
                Return ResourceManager.GetString("err0022", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This date should be double-dated.
        '''</summary>
        Friend ReadOnly Property err0023() As String
            Get
                Return ResourceManager.GetString("err0023", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Day number should be numeric.
        '''</summary>
        Friend ReadOnly Property err0024() As String
            Get
                Return ResourceManager.GetString("err0024", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to After 1751, double-dating does not apply.
        '''</summary>
        Friend ReadOnly Property err0025() As String
            Get
                Return ResourceManager.GetString("err0025", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Year was not a leap-year.
        '''</summary>
        Friend ReadOnly Property err0026() As String
            Get
                Return ResourceManager.GetString("err0026", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Century was not a leap-year.
        '''</summary>
        Friend ReadOnly Property err0027() As String
            Get
                Return ResourceManager.GetString("err0027", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to If separator characters (/- .) are used within a date, then they must be used consistently. They can not be mixed..
        '''</summary>
        Friend ReadOnly Property err0039() As String
            Get
                Return ResourceManager.GetString("err0039", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warning: The Age at Burial is over 100 years and is thus suspect.
        '''</summary>
        Friend ReadOnly Property err0041() As String
            Get
                Return ResourceManager.GetString("err0041", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Date of Baptism is before the Date of Birth.
        '''</summary>
        Friend ReadOnly Property err0049() As String
            Get
                Return ResourceManager.GetString("err0049", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Brides Age at marriage is over 100!.
        '''</summary>
        Friend ReadOnly Property err0058() As String
            Get
                Return ResourceManager.GetString("err0058", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Grooms Age at marriage is over 100!.
        '''</summary>
        Friend ReadOnly Property err0059() As String
            Get
                Return ResourceManager.GetString("err0059", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This person being married or buried is 100 years old or older. Is this correct?.
        '''</summary>
        Friend ReadOnly Property msgOldperson() As String
            Get
                Return ResourceManager.GetString("msgOldperson", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (?&lt;years&gt;\d{1,3})$|(?&lt;age&gt;\d{1,3}y)(?&lt;months&gt;\d{1,2}m)?(?&lt;weeks&gt;\d{1,2}w)?(?&lt;days&gt;\d{1,2}d)?$.
        '''</summary>
        Friend ReadOnly Property rgxMarriageAge() As String
            Get
                Return ResourceManager.GetString("rgxMarriageAge", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ^(?&lt;years&gt;\d{1,3})$|^(?&lt;vulgar&gt;\d{1,3}[\u00bc\u00bd\u00be])$|^(?&lt;units&gt;\d{1,3}y)?(?&lt;months&gt;\d{1,2}m)?(?&lt;weeks&gt;\d{1,2}w)?(?&lt;days&gt;\d{1,2}d)?$.
        '''</summary>
        Friend ReadOnly Property rgxMarriageAge1() As String
            Get
                Return ResourceManager.GetString("rgxMarriageAge1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ^(?&lt;year&gt;(?&lt;num1&gt;\d{1,3})(?&lt;unit1&gt;y)(?&lt;num2&gt;\d{1,3})(?&lt;unit2&gt;[dmw]))$.
        '''</summary>
        Friend ReadOnly Property rgxMarriageAgeComplex() As String
            Get
                Return ResourceManager.GetString("rgxMarriageAgeComplex", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ^(?&lt;year&gt;(?&lt;number&gt;\d{1,3})(?&lt;unit&gt;[dmw]?))$.
        '''</summary>
        Friend ReadOnly Property rgxMarriageAgeSimple() As String
            Get
                Return ResourceManager.GetString("rgxMarriageAgeSimple", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
